apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silly-demo
  template:
    metadata:
      labels:
        app: silly-demo
    spec:
      containers:
        - name: silly-demo
          image: {{ .Values.sillyDemo.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.sillyDemo.port }}
          env:
            - name: DB_ENDPOINT
              value: db
            - name: DB_PORT
              value: "{{ .Values.sillyDemo.db.port }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
