apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
data:
  init.sql: |
    \c db;
    CREATE TABLE IF NOT EXISTS videos (
      id VARCHAR(255) NOT NULL,
      title VARCHAR(255) NOT NULL
    );
